Ты опытный frontend разработчик на Next.js. Создай детальную структуру проекта для образовательного портала со следующими требованиями:

ТЕХНОЛОГИИ:
- Next.js 14 с App Router
- TypeScript строгий режим
- TailwindCSS + ShadCN UI
- React Query для state management
- next-intl для интернационализации
- Zod + React Hook Form для валидации

ОСНОВНЫЕ СТРАНИЦЫ И КОМПОНЕНТЫ:
1. Аутентификация (логин, регистрация, восстановление)
2. Дашборд с прогрессом обучения
3. Навигация по предметам → темам → урокам
4. Просмотр уроков с rich content
5. Интерфейс тестов с разными типами вопросов
6. Просмотр и скачивание сертификатов
7. Админ панель
8. Настройки пользователя

ЗАДАЧА:
Создай полную файловую структуру проекта (дерево папок до 3-го уровня) с описанием назначения каждой директории. Включи:

- App Router структуру с группами роутов
- Компоненты по категориям (ui, layout, features)
- Конфигурацию i18n
- API клиенты и хуки
- Типы TypeScript
- Утилиты и конфиги

Формат вывода: Markdown с деревом директорий и кратким описанием каждого файла/папки.
